Repository wecode-bootcamp-korea/13-watchandchill-backend, pull requests merged in 2020-10, with the labels that each got.

#2 [모델][Movies]Feature/movies info
  .gitignore
  movie/__init__.py
  movie/admin.py
  movie/apps.py
  movie/migrations/0001_initial.py
  movie/migrations/0002_auto_20201021_0951.py
  movie/migrations/0003_auto_20201021_0954.py
  movie/migrations/0004_auto_20201021_1103.py
  movie/migrations/0005_auto_20201022_0142.py
  movie/migrations/0006_auto_20201022_0159.py
  movie/migrations/0007_auto_20201022_0210.py
  movie/migrations/0008_auto_20201022_0237.py
  movie/migrations/0009_auto_20201022_0238.py
  movie/migrations/0010_auto_20201022_0428.py
  movie/migrations/0011_auto_20201022_0455.py
  movie/migrations/__init__.py
  movie/models.py
  movie/tests.py
  movie/urls.py
  movie/views.py
  watchapedia/__pycache__/settings.cpython-38.pyc
  watchapedia/__pycache__/urls.cpython-38.pyc
  watchapedia/settings.py
  watchapedia/urls.py
Labels: Status: 수정 요청

#1 [13-watchaandchill]user/models.py 완료
  .gitignore
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
  watchapedia/__pycache__/__init__.cpython-38.pyc
  watchapedia/__pycache__/settings.cpython-38.pyc
  watchapedia/__pycache__/urls.cpython-38.pyc
  watchapedia/settings.py
  watchapedia/urls.py
Labels: Status: 리뷰 요청

#4 Add : 회원가입, 로그인, 토큰 데코레이터
  movie/migrations/0001_initial.py
  movie/migrations/0002_auto_20201021_0951.py
  movie/migrations/0003_auto_20201021_0954.py
  movie/migrations/0004_auto_20201021_1103.py
  movie/migrations/0005_auto_20201022_0142.py
  movie/migrations/0006_auto_20201022_0159.py
  movie/migrations/0007_auto_20201022_0210.py
  movie/migrations/0008_auto_20201022_0237.py
  movie/migrations/0009_auto_20201022_0238.py
  movie/migrations/0010_auto_20201022_0428.py
  movie/migrations/0011_auto_20201022_0455.py
  movie/models.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/0001_initial.py
  review/migrations/0002_auto_20201026_1232.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/urls.py
  review/views.py
  user/migrations/0001_initial.py
  user/models.py
  user/urls.py
  user/utils.py
  user/views.py
  watchapedia/settings.py
  watchapedia/urls.py
Labels: Status: 리뷰 진행중

#3 [김창곤][뷰:메인페이지, 상세페이지]created main page and info views
  movie/migrations/0001_initial.py
  movie/migrations/0002_auto_20201021_0951.py
  movie/migrations/0003_auto_20201021_0954.py
  movie/migrations/0004_auto_20201021_1103.py
  movie/migrations/0005_auto_20201022_0142.py
  movie/migrations/0006_auto_20201022_0159.py
  movie/migrations/0007_auto_20201022_0210.py
  movie/migrations/0008_auto_20201022_0237.py
  movie/migrations/0009_auto_20201022_0238.py
  movie/migrations/0010_auto_20201022_0428.py
  movie/migrations/0011_auto_20201022_0455.py
  movie/models.py
  movie/urls.py
  movie/views.py
  user/urls.py
  user/utils.py
  user/views.py
  watchapedia/settings.py
  watchapedia/urls.py
Labels: Status: 리뷰 요청

#7 Feature/review
  movie/models.py
  movie/views.py
  review/models.py
  review/urls.py
  review/views.py
  user/urls.py
  user/utils.py
  user/views.py
  watchapedia/settings.py
  watchapedia/urls.py
Labels: Status: 수정 요청
